eureka:
  instance:
    statusPageUrlPath: /actuator/info
    healthCheckUrlPath: /actuator/health
    # docker 部署开启
    prefer-ip-address: true
    ipAddress: ${INSTANCE_HOST:172.18.147.199}
  client:
    serviceUrl:
      defaultZone: http://${EUREKA_HOST:172.18.147.199}:${EUREKA_PORT:8761}/eureka/
server:
  port: 8763
spring:
  application:
    name: j4sc-turbine-server
#  rabbitmq:
#    host: localhost
#    port: 5672
#    username: guest
#    password: guest
turbine:
  app-config: j4sc-gateway-server,j4sc-auth-server,bjt-system-server,bjt-user-server,bjt-api-server,bjt-carpark-server,bjt-park-server
  aggregator:
    cluster-config: default
  cluster-name-expression: new String("default")