server:
  port: 8761
spring:
  application:
    name: j4sc-service-server
eureka:
  server:
    #服务保护
    enable-self-preservation: false
#  instance:
#    hostname: LongRou
  client:
    registerWithEureka: false
    fetchRegistry: false
#    serviceUrl:
#      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/