server:
  port: 443
  ssl:
    client-auth: want
    key-store: classpath:214658546420890.pfx
    key-store-password: 214658546420890
    key-store-type: PKCS12
eureka:
  instance:
    statusPageUrlPath: /actuator/info
    healthCheckUrlPath: /actuator/health
    secure-port-enabled: true
    secure-port: 443
    non-secure-port-enabled: false
    # docker 部署开启
    prefer-ip-address: true
    #ip-address: 127.0.0.1
  client:
    serviceUrl:
      defaultZone: http://${EUREKA_HOST:172.18.147.199}:${EUREKA_PORT:8761}/eureka/

#请求和响应GZIP压缩支持
feign:
 hystrix:
    enabled: true
#  httpclient:
#    enabled: false
#  okhttp:
#    enabled: true
#  compression:
#    request:
#      enabled: true
#      mime-types: text/xml,application/xml,application/json
#      min-request-size: 2048
#    response:
#      enabled: true

spring:
  application:
      name: j4sc-gateway-server
  cloud:
    bus:
      enabled: false
  zipkin:
    base-url: http://${ZIPKIN_HOST:172.18.147.199}:9411/
    sender:
      type: web
    service:
      name: j4sc-gateway
  sleuth:
    sampler:
      probability: 0.1
  redis:
    database: 1
    host: ${REDIS_HOST:172.18.147.199}
    port: ${REDIS_PORT:6379}
    password: mWAeTehZJrn4lLbsDRU1CQ==
    jedis:
      pool:
        max-active: 60
#  rabbitmq:
#      host: ${RABBIT_MQ_HOST:172.18.147.199}
#      port:  ${RABBIT_MQ_PORT:5672}
#      username: guest
#      password: guest
#  sleuth:
#    enabled: true
#    http:
#      legacy:
#        enabled: true
  cloud:
    gateway:
      locator:
        enabled: true #开启路由
      routes:
      # =====================================
#      - id: j4sc-upms-server
#        uri: lb://j4sc-upms-server
#        order: 8000
#        predicates:
#        - Path=/upms/**
#        filters:
#        - StripPrefix=1 #去除upms
      - id: j4sc-eureka
        uri: http://172.18.147.199:8761/
        predicates:
        - Path=/eureka/**
        filters:
        - StripPrefix=1
      - id: j4sc-zipkin
        uri: http://172.18.147.199:9411/
        predicates:
        - Path=/zipkin/**
        filters:
        - StripPrefix=1
      - id: j4sc-turbine-server
        uri: lb:https://j4sc-turbine-server
        predicates:
        - Path=/turbine/**
        filters:
        - StripPrefix=1
      - id: j4sc-oss-server
        uri: lb:https://j4sc-oss-server
        order: 8000
        predicates:
        - Path=/oss/**
        filters:
        - StripPrefix=1
      - id: j4sc-turbine-server
        uri: lb:https://j4sc-turbine-server
        order: 8000
        predicates:
        - Path=/turbine/**
        filters:
        - StripPrefix=1
      - id: j4sc-auth-server
        uri: lb:https://j4sc-auth-server
        order: 8000
        predicates:
        - Path=/admin/**
        filters:
        - StripPrefix=1 #去除app
      - id: bjt-api-server
        uri: lb:https://bjt-api-server
        order: 8000
        predicates:
        - Path=/app/**
        filters:
        - StripPrefix=1
logging:
  level:
    com.j4sc.gatetay.server: info
#不拦截地址 "," 分割
j4sc:
  ignore:
    url: /auth
  auth:
    token-header: j4sc-token

management:
#  endpoints:
#    web:
#      exposure:
#        include: '*'
  security:
    enabled: false


#gate:
#  ignore:
#    startWith: /jwt


#auth:
#  serviceId: ace-auth
#  user:
#    token-header: Authorization
#  client:
#    token-header: x-client-token
#    id: ace-gate  #不填则默认读取spring.application.name
#    secret: 123456
